' =============================================================
' PATTERN DATA BANKASI - 142 BENZERSIZ PATTERN
' 5 kaynak dosyadan birlestirilmis, tekrarlar kaldirilmis,
' ASM kodlari optimize edilmis
' =============================================================
PatternData:

' 11 karakter: Ultra-spesifik multi-cell loop idiomlari
DATA "[->+>+<+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[->+>+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"

' 10 karakter: Uzun meta sistem + aritmetik
DATA "0++++++++@", "JSR $FFD5 ; KERNAL LOAD"
DATA ">>>>>>>>>>", "TYA : CLC : ADC #10 : TAY : BCC *+4 : INC PTR+1"
DATA "++++++++++", "LDA (PTR),Y : CLC : ADC #10 : STA (PTR),Y"
DATA "----------", "LDA (PTR),Y : SEC : SBC #10 : STA (PTR),Y"

' 9 karakter: Kompleks loop + blok + aritmetik
DATA "[->>>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : INY : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[->+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[>+>+<<-]", "INY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "0>0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0+++++++@", "JSR $FFD8 ; KERNAL SAVE"
DATA ">>>>>>>>>", "TYA : CLC : ADC #9 : TAY : BCC *+4 : INC PTR+1"
DATA "+++++++++", "LDA (PTR),Y : CLC : ADC #9 : STA (PTR),Y"
DATA "---------", "LDA (PTR),Y : SEC : SBC #9 : STA (PTR),Y"

' 8 karakter: Gelişmis aritmetik + stabilizasyon
DATA "[<+>+>-]", "DEY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y : DEY"
DATA "0++++++@", "JSR $E544 : JSR $E518 ; Full Clear+Home"
DATA "<<<<<<<<", "TYA : SEC : SBC #8 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>>>>", "TYA : CLC : ADC #8 : TAY : BCC *+4 : INC PTR+1"
DATA "++++++--", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "------++", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"
DATA "++++++++", "LDA (PTR),Y : CLC : ADC #8 : STA (PTR),Y"
DATA "--------", "LDA (PTR),Y : SEC : SBC #8 : STA (PTR),Y"

' 7 karakter: Meta + blok + pointer
DATA "0+++++@", "JSR $E094 : AND #$0F : STA (PTR),Y ; Random nibble"
DATA "0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "<<<<<<<", "TYA : SEC : SBC #7 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>>>", "TYA : CLC : ADC #7 : TAY : BCC *+4 : INC PTR+1"

' 6 karakter: Loop idiomlari + meta
DATA "[-][+]", "LDA #0 : STA (PTR),Y"
DATA "[-<+>]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY"
DATA "[->+<]", "LDA (PTR),Y : CLC : INY : ADC (PTR),Y : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[<+>-]", "DEY : LDA (PTR),Y : CLC : INY : ADC (PTR),Y : DEY : STA (PTR),Y : INY : LDA #0 : STA (PTR),Y"
DATA "[>+<-]", "INY : LDA (PTR),Y : CLC : DEY : ADC (PTR),Y : INY : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[-<->]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : STA (PTR),Y : INY"
DATA "[->-<]", "LDA (PTR),Y : STA $02 : INY : LDA (PTR),Y : SEC : SBC $02 : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "$>$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : DEY : PLA : STA (PTR),Y : DEY : TXA : STA (PTR),Y"
DATA "0++++@", "JSR $E094 ; RND to Cell"
DATA "<<<<<<", "TYA : SEC : SBC #6 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>>", "TYA : CLC : ADC #6 : TAY : BCC *+4 : INC PTR+1"
DATA "++++++", "LDA (PTR),Y : CLC : ADC #6 : STA (PTR),Y"
DATA "------", "LDA (PTR),Y : SEC : SBC #6 : STA (PTR),Y"

' 5 karakter: Blok + stack + aritmetik
DATA "[<->]", "DEY : LDA (PTR),Y : TAX : INY : LDA (PTR),Y : STA (PTR),Y : DEY : TXA : STA (PTR),Y"
DATA "[-]<+", "LDA #0 : STA (PTR),Y : DEY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : INY"
DATA "[-]>+", "LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : DEY"
DATA "!!!!!", "LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY : DEY"
DATA "0!0!0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY : INY : STA (PTR),Y"
DATA ". . .", "LDA (PTR),Y : JSR $FFD2 : LDA #$20 : JSR $FFD2 : LDA (PTR),Y : JSR $FFD2"
DATA "0+++@", "LDA #3 : JSR $E544"
DATA "0>!>0", "LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "+&+&+", "LDA (PTR),Y : CLC : ADC #1 : STA $02 : INY : LDA (PTR),Y : ADC $02 : STA (PTR),Y : DEY"
DATA "++&++", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "--|--", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"
DATA "0++++", "LDA #4 : STA (PTR),Y"
DATA "<<<<<", "TYA : SEC : SBC #5 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>", "TYA : CLC : ADC #5 : TAY : BCC *+4 : INC PTR+1"
DATA "+++++", "LDA (PTR),Y : CLC : ADC #5 : STA (PTR),Y"
DATA "-----", "LDA (PTR),Y : SEC : SBC #5 : STA (PTR),Y"

' 4 karakter: Temel folding + I/O + stack
DATA "[-]<", "LDA #0 : STA (PTR),Y : DEY : BCS *+4 : DEC PTR+1"
DATA "[-]>", "LDA #0 : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA "$<$%", "LDA (PTR),Y : PHA : DEY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : INY : STA (PTR),Y"
DATA "$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : DEY : STA (PTR),Y"
DATA "0$0%", "LDA #0 : STA (PTR),Y : PHA : INY : LDA #0 : STA (PTR),Y : PHA : DEY"
DATA "%<%<", "PLA : STA (PTR),Y : DEY : PLA : STA (PTR),Y : DEY"
DATA "$+$-", "LDA (PTR),Y : PHA : CLC : ADC #1 : STA (PTR),Y : SEC : SBC #2 : STA (PTR),Y : PLA"
DATA "!!!0", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : LDA #0 : STA (PTR),Y"
DATA ".0.0", "LDA (PTR),Y : PHA : JSR $FFD2 : PLA : LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : PHA : JSR $FFD2 : PLA : LDA #0 : STA (PTR),Y : DEY"
DATA "0+@>", "JSR $E544 : INY"
DATA "!!!>", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : INY : STX (PTR),Y"
DATA "???>", "LDA (PTR),Y : TAX : DEY : STX (PTR),Y : DEY : STX (PTR),Y : DEY : STX (PTR),Y"
DATA "0++@", "JSR $E518 ; HOME"
DATA "!!!!", "LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY"
DATA "+++@", "LDA #3 : JSR $E544"
DATA "0<<<", "LDA #0 : STA (PTR),Y : TYA : SEC : SBC #3 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>0", "TYA : CLC : ADC #3 : TAY : BCC *+4 : INC PTR+1 : LDA #0 : STA (PTR),Y"
DATA ">><<", "NOP"
DATA "0+++", "LDA #3 : STA (PTR),Y"
DATA "+-+-", "NOP"
DATA "++++", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "----", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"

' 3 karakter: Kisa folding + I/O + bitwise
DATA "[<]", "DEY : LDA (PTR),Y : BEQ *+3"
DATA "[>]", "INY : LDA (PTR),Y : BEQ *+3"
DATA "[+]", "LDA #0 : STA (PTR),Y"
DATA "[-]", "LDA #0 : STA (PTR),Y"
DATA "@@.", "JSR $E544 : JSR $E518 : LDA (PTR),Y : JSR $FFD2"
DATA "@@@", "JSR $E544 : JSR $E518 : JSR $E544 ; Clear-Home-Clear"
DATA "$0%", "LDA (PTR),Y : PHA : LDA #0 : STA (PTR),Y : PLA : STA (PTR),Y"
DATA "0.@", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $E544"
DATA "0!@", "JSR $E544 : INY"
DATA "0..", "LDA #0 : STA (PTR),Y : JSR $FFD2 : LDA #0 : JSR $FFD2"
DATA "0+@", "JSR $E544 ; CLS"
DATA ",,,", "JSR $FFCF : STA (PTR),Y : INY : JSR $FFCF : STA (PTR),Y : INY : JSR $FFCF : STA (PTR),Y : DEY : DEY"
DATA "!!>", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "??<", "LDA (PTR),Y : DEY : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "0^^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "!!!", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : DEY : DEY"
DATA "0&0", "LDA #0 : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y : DEY"
DATA "0|0", "LDA #0 : SEC : SBC (PTR),Y : INY : STA (PTR),Y : DEY"
DATA "++.", "LDA (PTR),Y : CLC : ADC #2 : PHA : JSR $FFD2 : PLA : STA (PTR),Y"
DATA "--.", "LDA (PTR),Y : SEC : SBC #2 : PHA : JSR $FFD2 : PLA : STA (PTR),Y"
DATA "0<0", "LDA #0 : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y"
DATA "&&&", "LDA (PTR),Y : ASL A : ASL A : STA (PTR),Y"
DATA "|||", "LDA (PTR),Y : LSR A : LSR A : STA (PTR),Y"
DATA "+&+", "LDA (PTR),Y : CLC : ADC #1 : STA $02 : INY : LDA (PTR),Y : ADC $02 : STA (PTR),Y : DEY"
DATA "++&", "LDA (PTR),Y : CLC : ADC #2 : STA $02 : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"
DATA "0++", "LDA #2 : STA (PTR),Y"
DATA "<<<", "TYA : SEC : SBC #3 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>", "TYA : CLC : ADC #3 : TAY : BCC *+4 : INC PTR+1"

' 2 karakter: Minimal folding + stabilizasyon
DATA "@.", "LDA (PTR),Y : JSR $FFD2"
DATA "@@", "JSR $E544 : JSR $E518 ; Clear and Home"
DATA "0@", "JSR $E544 ; CLS"
DATA "@0", "JSR $E544 : STA (PTR),Y"
DATA ",.", "JSR $FFCF : PHA : JSR $FFD2 : PLA : STA (PTR),Y"
DATA ".,", "LDA (PTR),Y : PHA : JSR $FFD2 : PLA : JSR $FFCF : STA (PTR),Y"
DATA "@>", "LDA (PTR),Y : JSR $E094 : INY : STA (PTR),Y"
DATA "0$", "LDA #0 : STA (PTR),Y : PHA"
DATA "$>", "LDA (PTR),Y : PHA : INY : BNE *+4 : INC PTR+1"
DATA "<%", "TYA : BNE *+4 : DEC PTR+1 : DEY : PLA : STA (PTR),Y"
DATA "+$", "LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : PHA"
DATA "-$", "LDA (PTR),Y : SEC : SBC #1 : STA (PTR),Y : PHA"
DATA ".0", "LDA (PTR),Y : PHA : JSR $FFD2 : PLA : LDA #0 : STA (PTR),Y"
DATA ",<", "JSR $FFCF : STA (PTR),Y : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA ",>", "JSR $FFCF : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA ".<", "LDA (PTR),Y : JSR $FFD2 : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA ".>", "LDA (PTR),Y : JSR $FFD2 : INY : BNE *+4 : INC PTR+1"
DATA "..", "LDA (PTR),Y : PHA : JSR $FFD2 : PLA : PHA : JSR $FFD2 : PLA"
DATA "!>", "LDA (PTR),Y : INY : STA (PTR),Y"
DATA "0&", "LDA #0 : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y : DEY"
DATA "0^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "0|", "LDA #0 : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "?<", "LDA (PTR),Y : DEY : STA (PTR),Y"
DATA "^0", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1 : LDA #0 : STA (PTR),Y"
DATA "!!", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "0+", "LDA #1 : STA (PTR),Y"
DATA "0-", "LDA #255 : STA (PTR),Y"
DATA "&&", "LDA (PTR),Y : ASL A : STA (PTR),Y"
DATA "^^", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "||", "LDA (PTR),Y : LSR A : STA (PTR),Y"
DATA "00", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY"
DATA "<<", "TYA : SEC : SBC #2 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>", "TYA : CLC : ADC #2 : TAY : BCC *+4 : INC PTR+1"
DATA "++", "LDA (PTR),Y : CLC : ADC #2 : STA (PTR),Y"
DATA "--", "LDA (PTR),Y : SEC : SBC #2 : STA (PTR),Y"

DATA "__END__", "__END__"