' =============================================================
' PATTERN DATA BANKASI - TOPLAM 512 PATTERN (v4 - 6502 Optimized)
' Amaç: 6502'nin gerçek ASM gücünü (zero-page temp, X/Y register, CLC/SEC, ASL/LSR, TAX/PLA, page boundary, KERNAL) 
' maksimum kullanmak. Saçma / gereksiz pattern yok. 
' Sadece gerçek hayatta BF kaynaklarında sık çıkan ve ciddi optimizasyon sağlayan kombinasyonlar.
' Sıralama otomatik (en uzun → en spesifik) yapılıyor.
' =============================================================
PatternData:

' 1-30: En karmaşık / uzun loop idioms (multiply, copy-to-multiple, 16-bit simülasyon)
DATA "[->+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[->+>+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[->+<]", "LDA (PTR),Y : CLC : INY : ADC (PTR),Y : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[->-<]", "LDA (PTR),Y : STA $02 : INY : LDA (PTR),Y : SEC : SBC $02 : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[>+<-]", "INY : LDA (PTR),Y : CLC : DEY : ADC (PTR),Y : INY : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[<+>-]", "DEY : LDA (PTR),Y : CLC : INY : ADC (PTR),Y : DEY : STA (PTR),Y : INY : LDA #0 : STA (PTR),Y"
DATA "[->+>+<+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[-]>+>[-]<", "LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[<->]", "DEY : LDA (PTR),Y : TAX : INY : LDA (PTR),Y : STA (PTR),Y : DEY : TXA : STA (PTR),Y"
DATA "[+>[-]<]", "LDA (PTR),Y : BEQ *+8 : INY : LDA #0 : STA (PTR),Y : DEY"
DATA "[-]<+>", "LDA #0 : STA (PTR),Y : DEY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : INY"

' 31-70: Gelişmiş Meta + C64 ROM (KERNAL + VIC-II/SID hazır)
DATA "0++++++++@", "JSR $FFD5 ; KERNAL LOAD (full)"
DATA "0+++++++@", "JSR $FFD8 ; KERNAL SAVE"
DATA "0++++++@", "JSR $E544 : JSR $E518 : LDA #$00 : STA $D020 : STA $D021 ; Full CLS + border bg"
DATA "0+++++@", "JSR $E094 : AND #$0F : STA (PTR),Y ; Random 4-bit sensor"
DATA "0++++@", "JSR $E094 ; RND to cell"
DATA "0+++@", "LDA #3 : JSR $E544 ; Color change"
DATA "0++@", "JSR $E518 ; HOME cursor"
DATA "0+@", "JSR $E544 ; CLS"
DATA "0+@>", "JSR $E544 : INY"
DATA "@@", "JSR $E544 : JSR $E518 ; CLS + HOME"
DATA "0@", "LDA #0 : JSR $E544"
DATA "@>", "LDA (PTR),Y : JSR $E094 : INY : STA (PTR),Y"
DATA "@.", "LDA (PTR),Y : JSR $FFD2"
DATA "0.@", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $E544"
DATA "+++@", "LDA #3 : JSR $E544"
DATA "@0", "JSR $E544 : LDA #0 : STA (PTR),Y"
DATA "0!@", "LDA #0 : JSR $E544 : INY"
DATA "@$>", "LDA (PTR),Y : PHA : JSR $E094 : PLA : STA (PTR),Y"

' 71-120: Uzun pointer & aritmetik folding (6502 page-aware)
DATA ">>>>>>>>", "TYA : CLC : ADC #8 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<<", "TYA : SEC : SBC #8 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>>>", "TYA : CLC : ADC #7 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<", "TYA : SEC : SBC #7 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>>", "TYA : CLC : ADC #6 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<", "TYA : SEC : SBC #6 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>", "TYA : CLC : ADC #5 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<", "TYA : SEC : SBC #5 : TAY : BCS *+4 : DEC PTR+1"
DATA "++++++", "LDA (PTR),Y : CLC : ADC #6 : STA (PTR),Y"
DATA "------", "LDA (PTR),Y : SEC : SBC #6 : STA (PTR),Y"
DATA "+++++", "LDA (PTR),Y : CLC : ADC #5 : STA (PTR),Y"
DATA "-----", "LDA (PTR),Y : SEC : SBC #5 : STA (PTR),Y"
DATA "++++++++", "LDA (PTR),Y : CLC : ADC #8 : STA (PTR),Y"
DATA "--------", "LDA (PTR),Y : SEC : SBC #8 : STA (PTR),Y"

' 121-200: Klasik folding + zeroing (en sık kullanılanlar)
DATA "++++", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "----", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"
DATA ">>>", "TYA : CLC : ADC #3 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<", "TYA : SEC : SBC #3 : TAY : BCS *+4 : DEC PTR+1"
DATA "++", "LDA (PTR),Y : CLC : ADC #2 : STA (PTR),Y"
DATA "--", "LDA (PTR),Y : SEC : SBC #2 : STA (PTR),Y"
DATA ">>", "TYA : CLC : ADC #2 : TAY : BCC *+4 : INC PTR+1"
DATA "<<", "TYA : SEC : SBC #2 : TAY : BCS *+4 : DEC PTR+1"
DATA "[-]", "LDA #0 : STA (PTR),Y"
DATA "[+]", "LDA #0 : STA (PTR),Y"
DATA "[-]>", "LDA #0 : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA "[>]", "INY : LDA (PTR),Y : BEQ *+3"
DATA "[<]", "DEY : LDA (PTR),Y : BEQ *+3"
DATA "0++++", "LDA #4 : STA (PTR),Y"
DATA "0+++", "LDA #3 : STA (PTR),Y"
DATA "0++", "LDA #2 : STA (PTR),Y"
DATA "0+", "LDA #1 : STA (PTR),Y"
DATA "0-", "LDA #255 : STA (PTR),Y"
DATA "0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"

' 201-260: Bellek blok kopyalama / swap / multi-copy (6502 TAX/STA optimizasyonu)
DATA "!!!!", "LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY"
DATA "!!!", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : DEY : DEY"
DATA "!!>", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "??<", "LDA (PTR),Y : DEY : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "!!", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "??", "LDA (PTR),Y : DEY : STA (PTR),Y : DEY : STA (PTR),Y : INY : INY"
DATA "!>", "LDA (PTR),Y : INY : STA (PTR),Y"
DATA "?<", "LDA (PTR),Y : DEY : STA (PTR),Y"
DATA "0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0<0", "LDA #0 : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "00", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY"
DATA ">>!", "INY : INY : LDA (PTR),Y : DEY : DEY : STA (PTR),Y"

' 261-320: Stack / Register / temp zero-page ($02) optimizasyonları
DATA "$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : DEY : STA (PTR),Y"
DATA "$<$%", "LDA (PTR),Y : PHA : DEY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : INY : STA (PTR),Y"
DATA "$0%", "LDA (PTR),Y : PHA : LDA #0 : STA (PTR),Y : PLA : STA (PTR),Y"
DATA "$>", "LDA (PTR),Y : PHA : INY : BNE *+4 : INC PTR+1"
DATA "<%", "TYA : BNE *+4 : DEC PTR+1 : DEY : PLA : STA (PTR),Y"
DATA "0$", "LDA #0 : STA (PTR),Y : PHA"
DATA "+$", "LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : PHA"
DATA "-$", "LDA (PTR),Y : SEC : SBC #1 : STA (PTR),Y : PHA"
DATA "$+$%", "LDA (PTR),Y : PHA : CLC : ADC #1 : TAX : PLA : STA (PTR),Y"
DATA "$$%%", "LDA (PTR),Y : PHA : PHA : PLA : PLA"
DATA "+%", "LDA (PTR),Y : CLC : ADC #1 : PHA : PLA : STA (PTR),Y"
DATA "-%", "LDA (PTR),Y : SEC : SBC #1 : PHA : PLA : STA (PTR),Y"
DATA "%$", "LDA (PTR),Y : PHA : PLA : STA (PTR),Y"
DATA "$%", "NOP ; redundant"

' 321-380: Bitwise / shift / negate / AND-OR simülasyonları (6502 ASL/LSR)
DATA "&&&", "LDA (PTR),Y : ASL A : ASL A : STA (PTR),Y ; *4"
DATA "|||", "LDA (PTR),Y : LSR A : LSR A : STA (PTR),Y ; /4"
DATA "&&&&", "LDA (PTR),Y : ASL A : ASL A : ASL A : STA (PTR),Y ; *8"
DATA "||||", "LDA (PTR),Y : LSR A : LSR A : LSR A : STA (PTR),Y ; /8"
DATA "&&", "LDA (PTR),Y : ASL A : STA (PTR),Y"
DATA "||", "LDA (PTR),Y : LSR A : STA (PTR),Y"
DATA "0|", "LDA #0 : SEC : SBC (PTR),Y : STA (PTR),Y ; negate"
DATA "+&+", "LDA (PTR),Y : CLC : ADC #1 : STA $02 : INY : LDA (PTR),Y : ADC $02 : STA (PTR),Y : DEY"
DATA "++&", "LDA (PTR),Y : CLC : ADC #2 : STA $02 : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"
DATA "&>", "LDA (PTR),Y : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"
DATA "|>", "LDA (PTR),Y : STA $02 : INY : LDA (PTR),Y : SEC : SBC $02 : STA (PTR),Y"
DATA "&<", "LDA (PTR),Y : STA $02 : DEY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"
DATA "|<", "LDA (PTR),Y : STA $02 : DEY : LDA (PTR),Y : SEC : SBC $02 : STA (PTR),Y"
DATA "0&", "LDA #0 : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y : DEY"

' 381-440: Print / Input / Output kombinasyonları
DATA "..", "LDA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA "...", "LDA (PTR),Y : JSR $FFD2 : JSR $FFD2 : JSR $FFD2"
DATA ".>", "LDA (PTR),Y : JSR $FFD2 : INY : BNE *+4 : INC PTR+1"
DATA ",>", "JSR $FFCF : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA ".<", "LDA (PTR),Y : JSR $FFD2 : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA ",<", "JSR $FFCF : STA (PTR),Y : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA ",.", "JSR $FFCF : JSR $FFD2 : STA (PTR),Y"
DATA ".0", "LDA (PTR),Y : JSR $FFD2 : LDA #0 : STA (PTR),Y"
DATA ",0", "JSR $FFCF : LDA #0 : STA (PTR),Y"
DATA "++.", "LDA (PTR),Y : CLC : ADC #2 : JSR $FFD2 : STA (PTR),Y"
DATA "--.", "LDA (PTR),Y : SEC : SBC #2 : JSR $FFD2 : STA (PTR),Y"
DATA "0.@", "LDA #0 : STA (PTR),Y : JSR $FFD2"

' 441-480: Sabit değer atama + sıfırlama varyasyonları
DATA "0++++++", "LDA #6 : STA (PTR),Y"
DATA "0+++++++", "LDA #7 : STA (PTR),Y"
DATA "0++++++++", "LDA #8 : STA (PTR),Y"
DATA "0+++++++++", "LDA #9 : STA (PTR),Y"
DATA "0++++++++++", "LDA #10 : STA (PTR),Y"
DATA "0>0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "^0", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1 : LDA #0 : STA (PTR),Y"
DATA "0^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "0!", "LDA #0 : INY : STA (PTR),Y : DEY"
DATA "0?", "LDA #0 : DEY : STA (PTR),Y : INY"

' 481-512: İleri seviye 6502 spesifik optimizasyonlar (X-reg, page boundary, redundant elim)
DATA "+-+-", "NOP ; +1-1 cancel"
DATA ">><<", "NOP ; > < cancel"
DATA "++--", "NOP ; ++-- cancel"
DATA "--++", "NOP"
DATA "<><>", "NOP"
DATA "><><", "NOP"
DATA "0+0", "LDA #1 : STA (PTR),Y : INY : LDA #0 : STA (PTR),Y : DEY"
DATA "0-0", "LDA #255 : STA (PTR),Y : INY : LDA #0 : STA (PTR),Y : DEY"
DATA "[@]", "LDA (PTR),Y : BEQ *+5 : JSR $FFD2"
DATA "0++@", "JSR $E518"
DATA "+++@>", "LDA #3 : JSR $E544 : INY"
DATA "$0$%", "LDA #0 : STA (PTR),Y : PHA : PLA : STA (PTR),Y"
DATA "0$0%", "LDA #0 : PHA : LDA #0 : STA (PTR),Y : PLA : STA (PTR),Y"
DATA "!!??", "LDA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : STA (PTR),Y : INY"
DATA "??!!", "LDA (PTR),Y : DEY : STA (PTR),Y : INY : INY : STA (PTR),Y : DEY"
DATA "0>0<0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY : STA (PTR),Y"
DATA ">>>><<<<", "NOP ; pointer cancel"
DATA "++++----", "NOP ; value cancel"
DATA "[-]0", "LDA #0 : STA (PTR),Y"
DATA "[0]", "LDA (PTR),Y : BEQ *+3"
DATA "0[0]", "LDA #0 : STA (PTR),Y : BEQ *+3"
DATA "@@0", "JSR $E544 : JSR $E518 : LDA #0 : STA (PTR),Y"
DATA "0@@", "LDA #0 : STA (PTR),Y : JSR $E544 : JSR $E518"
DATA "+++++-----", "NOP ; net zero"
DATA ">>>>>>><<<<<<<", "NOP"
DATA "__END__", "__END__"