' =============================================================
' PATTERN DATA BANKASI - TOPLAM 256 PATTERN
' =============================================================
PatternData:

' 1-20: En uzun ve en spesifik loop / complex idioms
DATA "[->+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[->+<]", "LDA (PTR),Y : CLC : INY : ADC (PTR),Y : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[->-<]", "LDA (PTR),Y : STA $02 : INY : LDA (PTR),Y : SEC : SBC $02 : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[>+<-]", "INY : LDA (PTR),Y : CLC : DEY : ADC (PTR),Y : INY : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[<+>-]", "DEY : LDA (PTR),Y : CLC : INY : ADC (PTR),Y : DEY : STA (PTR),Y : INY : LDA #0 : STA (PTR),Y"
DATA "[-]>+", "LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : DEY"
DATA "[-]<+", "LDA #0 : STA (PTR),Y : DEY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : INY"
DATA "[->+>+<+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[<->]", "DEY : LDA (PTR),Y : TAX : INY : LDA (PTR),Y : STA (PTR),Y : DEY : TXA : STA (PTR),Y"
DATA "[-][+]", "LDA #0 : STA (PTR),Y"

' 21-60: Meta / C64 ROM çağrıları
DATA "0++++++++@", "JSR $FFD5 ; KERNAL LOAD"
DATA "0+++++++@", "JSR $FFD8 ; KERNAL SAVE"
DATA "0++++++@", "JSR $E544 : JSR $E518 ; Full Clear + Home"
DATA "0+++++@", "JSR $E094 : AND #$0F : STA (PTR),Y"
DATA "0++++@", "JSR $E094"
DATA "0+++@", "LDA #3 : JSR $E544"
DATA "0++@", "JSR $E518 ; HOME"
DATA "0+@", "JSR $E544 ; CLS"
DATA "0+@>", "JSR $E544 : INY"
DATA "@@", "JSR $E544 : JSR $E518"
DATA "0@", "LDA #0 : JSR $E544"
DATA "@>", "LDA (PTR),Y : JSR $E094 : INY : STA (PTR),Y"
DATA "@.", "LDA (PTR),Y : JSR $FFD2"
DATA "0.@", "LDA #0 : STA (PTR),Y : JSR $FFD2"
DATA "+++@", "LDA #3 : JSR $E544"
DATA "0!@", "LDA #0 : JSR $E544 : INY"
DATA "@0", "JSR $E544 : LDA #0 : STA (PTR),Y"

' 61-100: Uzun pointer + aritmetik
DATA ">>>>>>>", "TYA : CLC : ADC #7 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<", "TYA : SEC : SBC #7 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>>", "TYA : CLC : ADC #6 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<", "TYA : SEC : SBC #6 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>", "TYA : CLC : ADC #5 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<", "TYA : SEC : SBC #5 : TAY : BCS *+4 : DEC PTR+1"
DATA "++++++", "LDA (PTR),Y : CLC : ADC #6 : STA (PTR),Y"
DATA "------", "LDA (PTR),Y : SEC : SBC #6 : STA (PTR),Y"
DATA "+++++", "LDA (PTR),Y : CLC : ADC #5 : STA (PTR),Y"
DATA "-----", "LDA (PTR),Y : SEC : SBC #5 : STA (PTR),Y"

' 101-160: Standart folding (en çok kullanılanlar)
DATA "++++", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "----", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"
DATA ">>>", "TYA : CLC : ADC #3 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<", "TYA : SEC : SBC #3 : TAY : BCS *+4 : DEC PTR+1"
DATA "++", "LDA (PTR),Y : CLC : ADC #2 : STA (PTR),Y"
DATA "--", "LDA (PTR),Y : SEC : SBC #2 : STA (PTR),Y"
DATA ">>", "TYA : CLC : ADC #2 : TAY : BCC *+4 : INC PTR+1"
DATA "<<", "TYA : SEC : SBC #2 : TAY : BCS *+4 : DEC PTR+1"
DATA "[-]", "LDA #0 : STA (PTR),Y"
DATA "[+]", "LDA #0 : STA (PTR),Y"
DATA "[-]>", "LDA #0 : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA "[>]", "INY : LDA (PTR),Y : BEQ *+3"
DATA "[<]", "DEY : LDA (PTR),Y : BEQ *+3"

' 161-200: Bellek blok + kopyalama
DATA "0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "!!!!", "LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY"
DATA "!!!", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : DEY : DEY"
DATA "!!>", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "??<", "LDA (PTR),Y : DEY : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "!!", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "00", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY"
DATA "0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0<0", "LDA #0 : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "!>", "LDA (PTR),Y : INY : STA (PTR),Y"
DATA "?<", "LDA (PTR),Y : DEY : STA (PTR),Y"

' 201-240: Stack & Register işlemleri
DATA "$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : DEY : STA (PTR),Y"
DATA "$<$%", "LDA (PTR),Y : PHA : DEY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : INY : STA (PTR),Y"
DATA "$0%", "LDA (PTR),Y : PHA : LDA #0 : STA (PTR),Y : PLA : STA (PTR),Y"
DATA "$>", "LDA (PTR),Y : PHA : INY : BNE *+4 : INC PTR+1"
DATA "<%", "TYA : BNE *+4 : DEC PTR+1 : DEY : PLA : STA (PTR),Y"
DATA "0$", "LDA #0 : STA (PTR),Y : PHA"
DATA "+$", "LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : PHA"
DATA "-$", "LDA (PTR),Y : SEC : SBC #1 : STA (PTR),Y : PHA"

' 241-256: Çeşitli faydalı kombinasyonlar
DATA "0++++", "LDA #4 : STA (PTR),Y"
DATA "0+++", "LDA #3 : STA (PTR),Y"
DATA "0++", "LDA #2 : STA (PTR),Y"
DATA "0+", "LDA #1 : STA (PTR),Y"
DATA "0-", "LDA #255 : STA (PTR),Y"
DATA "&&", "LDA (PTR),Y : ASL A : STA (PTR),Y"
DATA "||", "LDA (PTR),Y : LSR A : STA (PTR),Y"
DATA "0|", "LDA #0 : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "..", "LDA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA ".>", "LDA (PTR),Y : JSR $FFD2 : INY : BNE *+4 : INC PTR+1"
DATA ",>", "JSR $FFCF : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA "++.", "LDA (PTR),Y : CLC : ADC #2 : JSR $FFD2 : STA (PTR),Y"
DATA "--.", "LDA (PTR),Y : SEC : SBC #2 : JSR $FFD2 : STA (PTR),Y"
DATA "^0", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1 : LDA #0 : STA (PTR),Y"
DATA "0^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "__END__", "__END__"

' === YENİ PATTERNLER 257-512 ===

' 257-280: Gelişmiş Loop & Multi-cell transfer
DATA "[->+>+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[->>>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : INY : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[<+>+>-]", "DEY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y : DEY"
DATA "[-<+>]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY"
DATA "[-<->]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : STA (PTR),Y : INY"
DATA "[>+>+<<-]", "INY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y"

' 281-310: Daha fazla pointer folding (8+)
DATA ">>>>>>>>", "TYA : CLC : ADC #8 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<<", "TYA : SEC : SBC #8 : TAY : BCS *+4 : DEC PTR+1"
DATA ">>>>>>>", "TYA : CLC : ADC #7 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<", "TYA : SEC : SBC #7 : TAY : BCS *+4 : DEC PTR+1"
DATA "++++++++", "LDA (PTR),Y : CLC : ADC #8 : STA (PTR),Y"
DATA "--------", "LDA (PTR),Y : SEC : SBC #8 : STA (PTR),Y"
DATA "+++++++++", "LDA (PTR),Y : CLC : ADC #9 : STA (PTR),Y"
DATA "---------", "LDA (PTR),Y : SEC : SBC #9 : STA (PTR),Y"

' 311-350: Bellek blok + fill + copy
DATA "0>0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "!!!!!","LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY : DEY"
DATA "0!0!0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY : INY : STA (PTR),Y"
DATA "!!!>", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : INY : STX (PTR),Y"
DATA "???>", "LDA (PTR),Y : TAX : DEY : STX (PTR),Y : DEY : STX (PTR),Y : DEY : STX (PTR),Y"
DATA "0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"

' 351-400: Aritmetik + Bitwise kombinasyonları
DATA "+&+&+", "LDA (PTR),Y : CLC : ADC #1 : STA $02 : INY : LDA (PTR),Y : ADC $02 : STA (PTR),Y : DEY"
DATA "&&&", "LDA (PTR),Y : ASL A : ASL A : STA (PTR),Y"
DATA "|||", "LDA (PTR),Y : LSR A : LSR A : STA (PTR),Y"
DATA "0&0", "LDA #0 : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y : DEY"
DATA "0|0", "LDA #0 : SEC : SBC (PTR),Y : INY : STA (PTR),Y : DEY"
DATA "++&++", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "--|--", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"

' 401-450: I/O + Meta kombinasyonları
DATA ". . .", "LDA (PTR),Y : JSR $FFD2 : LDA #$20 : JSR $FFD2 : LDA (PTR),Y : JSR $FFD2"
DATA ",,,", "JSR $FFCF : STA (PTR),Y : INY : JSR $FFCF : STA (PTR),Y : INY : JSR $FFCF : STA (PTR),Y : DEY : DEY"
DATA ".0.0", "LDA (PTR),Y : JSR $FFD2 : LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : JSR $FFD2 : LDA #0 : STA (PTR),Y : DEY"
DATA "@@.", "JSR $E544 : JSR $E518 : LDA (PTR),Y : JSR $FFD2"
DATA "0..", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA ".,", "LDA (PTR),Y : JSR $FFD2 : JSR $FFCF : STA (PTR),Y"

' 451-480: Stack + Register ileri seviye
DATA "$>$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : DEY : PLA : STA (PTR),Y : DEY : TXA : STA (PTR),Y"
DATA "%<%<", "PLA : STA (PTR),Y : DEY : PLA : STA (PTR),Y : DEY"
DATA "$+$-", "LDA (PTR),Y : PHA : CLC : ADC #1 : STA (PTR),Y : SEC : SBC #2 : STA (PTR),Y : PLA"
DATA "0$0%", "LDA #0 : STA (PTR),Y : PHA : INY : LDA #0 : STA (PTR),Y : PHA : DEY"

' 481-512: Genel temizlik + stabilizasyon + C64 spesifik
DATA "++++++--", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "------++", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"
DATA ">><<", "NOP ; pointer stabilize"
DATA "+-+-", "NOP ; value stabilize"
DATA "0>!>0", "LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "^^", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "0^^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "@@@", "JSR $E544 : JSR $E518 : JSR $E544"
DATA "!!!0", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : LDA #0 : STA (PTR),Y"
DATA ">>>0", "TYA : CLC : ADC #3 : TAY : BCC *+4 : INC PTR+1 : LDA #0 : STA (PTR),Y"
DATA "0<<<", "LDA #0 : STA (PTR),Y : TYA : SEC : SBC #3 : TAY : BCS *+4 : DEC PTR+1"
DATA "__END__", "__END__"

PatternData:

' 1-50: En uzun ve spesifik loop / multi-cell idioms
DATA "[->+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[->+>+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[->>>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : INY : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[>+>+<<-]", "INY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "[-<+>]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY"
DATA "[-<->]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : STA (PTR),Y : INY"
DATA "[<+>+>-]", "DEY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y : DEY"
DATA "[-]>", "LDA #0 : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA "[-]<", "LDA #0 : STA (PTR),Y : DEY : BCS *+4 : DEC PTR+1"
DATA "[+]", "LDA #0 : STA (PTR),Y"
DATA "[-]", "LDA #0 : STA (PTR),Y"

' 51-100: Meta / C64 ROM çağrıları (öncelikli)
DATA "0++++++++@", "JSR $FFD5 ; KERNAL LOAD"
DATA "0+++++++@", "JSR $FFD8 ; KERNAL SAVE"
DATA "0++++++@", "JSR $E544 : JSR $E518"
DATA "0+++++@", "JSR $E094 : AND #$0F : STA (PTR),Y"
DATA "0++++@", "JSR $E094"
DATA "0+++@", "LDA #3 : JSR $E544"
DATA "0++@", "JSR $E518"
DATA "0+@", "JSR $E544"
DATA "@@", "JSR $E544 : JSR $E518"
DATA "0.@", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $E544"
DATA "@>", "LDA (PTR),Y : JSR $E094 : INY : STA (PTR),Y"
DATA "@.", "LDA (PTR),Y : JSR $FFD2"
DATA "0@", "LDA #0 : JSR $E544"
DATA "+++@", "LDA #3 : JSR $E544"

' 101-160: Pointer & Value folding (2-10)
DATA ">>>>>>>>", "TYA : CLC : ADC #8 : TAY : BCC *+4 : INC PTR+1"
DATA ">>>>>>>>>", "TYA : CLC : ADC #9 : TAY : BCC *+4 : INC PTR+1"
DATA ">>>>>>>>>>", "TYA : CLC : ADC #10 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<<", "TYA : SEC : SBC #8 : TAY : BCS *+4 : DEC PTR+1"
DATA "++++++++", "LDA (PTR),Y : CLC : ADC #8 : STA (PTR),Y"
DATA "+++++++++", "LDA (PTR),Y : CLC : ADC #9 : STA (PTR),Y"
DATA "++++++++++", "LDA (PTR),Y : CLC : ADC #10 : STA (PTR),Y"
DATA "--------", "LDA (PTR),Y : SEC : SBC #8 : STA (PTR),Y"
DATA "---------", "LDA (PTR),Y : SEC : SBC #9 : STA (PTR),Y"
DATA "----------", "LDA (PTR),Y : SEC : SBC #10 : STA (PTR),Y"
DATA ">>", "TYA : CLC : ADC #2 : TAY : BCC *+4 : INC PTR+1"
DATA "<<", "TYA : SEC : SBC #2 : TAY : BCS *+4 : DEC PTR+1"
DATA "++", "LDA (PTR),Y : CLC : ADC #2 : STA (PTR),Y"
DATA "--", "LDA (PTR),Y : SEC : SBC #2 : STA (PTR),Y"

' 161-220: Bellek blok kopyalama & fill
DATA "0>0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "!!!!!", "LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY : DEY"
DATA "!!!", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : DEY : DEY"
DATA "!!", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "00", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY"
DATA "!>", "LDA (PTR),Y : INY : STA (PTR),Y"
DATA "?<", "LDA (PTR),Y : DEY : STA (PTR),Y"

' 221-280: Stack & Register işlemleri
DATA "$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : DEY : STA (PTR),Y"
DATA "$<$%", "LDA (PTR),Y : PHA : DEY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : INY : STA (PTR),Y"
DATA "$0%", "LDA (PTR),Y : PHA : LDA #0 : STA (PTR),Y : PLA : STA (PTR),Y"
DATA "$>", "LDA (PTR),Y : PHA : INY : BNE *+4 : INC PTR+1"
DATA "<%", "TYA : BNE *+4 : DEC PTR+1 : DEY : PLA : STA (PTR),Y"
DATA "0$", "LDA #0 : STA (PTR),Y : PHA"
DATA "+$", "LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : PHA"
DATA "-$", "LDA (PTR),Y : SEC : SBC #1 : STA (PTR),Y : PHA"

' 281-340: Bitwise & Aritmetik kombinasyon
DATA "&&", "LDA (PTR),Y : ASL A : STA (PTR),Y"
DATA "&&&", "LDA (PTR),Y : ASL A : ASL A : STA (PTR),Y"
DATA "||", "LDA (PTR),Y : LSR A : STA (PTR),Y"
DATA "0&", "LDA #0 : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y : DEY"
DATA "0|", "LDA #0 : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "+&+", "LDA (PTR),Y : CLC : ADC #1 : STA $02 : INY : LDA (PTR),Y : ADC $02 : STA (PTR),Y : DEY"
DATA "++&", "LDA (PTR),Y : CLC : ADC #2 : STA $02 : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"

' 341-400: I/O kombinasyonları
DATA ".>", "LDA (PTR),Y : JSR $FFD2 : INY : BNE *+4 : INC PTR+1"
DATA ",>", "JSR $FFCF : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA ".<", "LDA (PTR),Y : JSR $FFD2 : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA ",<", "JSR $FFCF : STA (PTR),Y : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA "..", "LDA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA ",.", "JSR $FFCF : JSR $FFD2 : STA (PTR),Y"
DATA ".0", "LDA (PTR),Y : JSR $FFD2 : LDA #0 : STA (PTR),Y"
DATA "++.", "LDA (PTR),Y : CLC : ADC #2 : JSR $FFD2 : STA (PTR),Y"

' 401-460: Genel temizlik & sabit atamalar
DATA "0++++", "LDA #4 : STA (PTR),Y"
DATA "0+++", "LDA #3 : STA (PTR),Y"
DATA "0++", "LDA #2 : STA (PTR),Y"
DATA "0+", "LDA #1 : STA (PTR),Y"
DATA "0-", "LDA #255 : STA (PTR),Y"
DATA "0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0<0", "LDA #0 : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "^0", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1 : LDA #0 : STA (PTR),Y"
DATA "0^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"

' 461-512: Karışık optimize + stabilizasyon
DATA "++++++", "LDA (PTR),Y : CLC : ADC #6 : STA (PTR),Y"
DATA "------", "LDA (PTR),Y : SEC : SBC #6 : STA (PTR),Y"
DATA ">>>>>>", "TYA : CLC : ADC #6 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<", "TYA : SEC : SBC #6 : TAY : BCS *+4 : DEC PTR+1"
DATA ">><<", "NOP"
DATA "+-+-", "NOP"
DATA "@@@", "JSR $E544 : JSR $E518 : JSR $E544"
DATA "0..", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA "!!!0", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : LDA #0 : STA (PTR),Y"
DATA "0!0!0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY : INY : STA (PTR),Y"
DATA "__END__", "__END__"

PatternData:

' 1-50: En uzun ve spesifik loop / multi-cell idioms
DATA "[->+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[->+>+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[->>>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : INY : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[>+>+<<-]", "INY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "[-<+>]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY"
DATA "[-<->]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : STA (PTR),Y : INY"
DATA "[<+>+>-]", "DEY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y : DEY"
DATA "[-]>", "LDA #0 : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA "[-]<", "LDA #0 : STA (PTR),Y : DEY : BCS *+4 : DEC PTR+1"
DATA "[+]", "LDA #0 : STA (PTR),Y"
DATA "[-]", "LDA #0 : STA (PTR),Y"

' 51-100: Meta / C64 ROM çağrıları (öncelikli)
DATA "0++++++++@", "JSR $FFD5 ; KERNAL LOAD"
DATA "0+++++++@", "JSR $FFD8 ; KERNAL SAVE"
DATA "0++++++@", "JSR $E544 : JSR $E518"
DATA "0+++++@", "JSR $E094 : AND #$0F : STA (PTR),Y"
DATA "0++++@", "JSR $E094"
DATA "0+++@", "LDA #3 : JSR $E544"
DATA "0++@", "JSR $E518"
DATA "0+@", "JSR $E544"
DATA "@@", "JSR $E544 : JSR $E518"
DATA "0.@", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $E544"
DATA "@>", "LDA (PTR),Y : JSR $E094 : INY : STA (PTR),Y"
DATA "@.", "LDA (PTR),Y : JSR $FFD2"
DATA "0@", "LDA #0 : JSR $E544"
DATA "+++@", "LDA #3 : JSR $E544"

' 101-160: Pointer & Value folding (2-10)
DATA ">>>>>>>>", "TYA : CLC : ADC #8 : TAY : BCC *+4 : INC PTR+1"
DATA ">>>>>>>>>", "TYA : CLC : ADC #9 : TAY : BCC *+4 : INC PTR+1"
DATA ">>>>>>>>>>", "TYA : CLC : ADC #10 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<<", "TYA : SEC : SBC #8 : TAY : BCS *+4 : DEC PTR+1"
DATA "++++++++", "LDA (PTR),Y : CLC : ADC #8 : STA (PTR),Y"
DATA "+++++++++", "LDA (PTR),Y : CLC : ADC #9 : STA (PTR),Y"
DATA "++++++++++", "LDA (PTR),Y : CLC : ADC #10 : STA (PTR),Y"
DATA "--------", "LDA (PTR),Y : SEC : SBC #8 : STA (PTR),Y"
DATA "---------", "LDA (PTR),Y : SEC : SBC #9 : STA (PTR),Y"
DATA "----------", "LDA (PTR),Y : SEC : SBC #10 : STA (PTR),Y"
DATA ">>", "TYA : CLC : ADC #2 : TAY : BCC *+4 : INC PTR+1"
DATA "<<", "TYA : SEC : SBC #2 : TAY : BCS *+4 : DEC PTR+1"
DATA "++", "LDA (PTR),Y : CLC : ADC #2 : STA (PTR),Y"
DATA "--", "LDA (PTR),Y : SEC : SBC #2 : STA (PTR),Y"

' 161-220: Bellek blok kopyalama & fill
DATA "0>0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "!!!!!", "LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY : DEY"
DATA "!!!", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : DEY : DEY"
DATA "!!", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "00", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY"
DATA "!>", "LDA (PTR),Y : INY : STA (PTR),Y"
DATA "?<", "LDA (PTR),Y : DEY : STA (PTR),Y"

' 221-280: Stack & Register işlemleri
DATA "$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : DEY : STA (PTR),Y"
DATA "$<$%", "LDA (PTR),Y : PHA : DEY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : INY : STA (PTR),Y"
DATA "$0%", "LDA (PTR),Y : PHA : LDA #0 : STA (PTR),Y : PLA : STA (PTR),Y"
DATA "$>", "LDA (PTR),Y : PHA : INY : BNE *+4 : INC PTR+1"
DATA "<%", "TYA : BNE *+4 : DEC PTR+1 : DEY : PLA : STA (PTR),Y"
DATA "0$", "LDA #0 : STA (PTR),Y : PHA"
DATA "+$", "LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : PHA"
DATA "-$", "LDA (PTR),Y : SEC : SBC #1 : STA (PTR),Y : PHA"

' 281-340: Bitwise & Aritmetik kombinasyon
DATA "&&", "LDA (PTR),Y : ASL A : STA (PTR),Y"
DATA "&&&", "LDA (PTR),Y : ASL A : ASL A : STA (PTR),Y"
DATA "||", "LDA (PTR),Y : LSR A : STA (PTR),Y"
DATA "0&", "LDA #0 : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y : DEY"
DATA "0|", "LDA #0 : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "+&+", "LDA (PTR),Y : CLC : ADC #1 : STA $02 : INY : LDA (PTR),Y : ADC $02 : STA (PTR),Y : DEY"
DATA "++&", "LDA (PTR),Y : CLC : ADC #2 : STA $02 : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"

' 341-400: I/O kombinasyonları
DATA ".>", "LDA (PTR),Y : JSR $FFD2 : INY : BNE *+4 : INC PTR+1"
DATA ",>", "JSR $FFCF : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA ".<", "LDA (PTR),Y : JSR $FFD2 : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA ",<", "JSR $FFCF : STA (PTR),Y : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA "..", "LDA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA ",.", "JSR $FFCF : JSR $FFD2 : STA (PTR),Y"
DATA ".0", "LDA (PTR),Y : JSR $FFD2 : LDA #0 : STA (PTR),Y"
DATA "++.", "LDA (PTR),Y : CLC : ADC #2 : JSR $FFD2 : STA (PTR),Y"

' 401-460: Genel temizlik & sabit atamalar
DATA "0++++", "LDA #4 : STA (PTR),Y"
DATA "0+++", "LDA #3 : STA (PTR),Y"
DATA "0++", "LDA #2 : STA (PTR),Y"
DATA "0+", "LDA #1 : STA (PTR),Y"
DATA "0-", "LDA #255 : STA (PTR),Y"
DATA "0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0<0", "LDA #0 : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "^0", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1 : LDA #0 : STA (PTR),Y"
DATA "0^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"

' 461-512: Karışık optimize + stabilizasyon
DATA "++++++", "LDA (PTR),Y : CLC : ADC #6 : STA (PTR),Y"
DATA "------", "LDA (PTR),Y : SEC : SBC #6 : STA (PTR),Y"
DATA ">>>>>>", "TYA : CLC : ADC #6 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<", "TYA : SEC : SBC #6 : TAY : BCS *+4 : DEC PTR+1"
DATA ">><<", "NOP"
DATA "+-+-", "NOP"
DATA "@@@", "JSR $E544 : JSR $E518 : JSR $E544"
DATA "0..", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA "!!!0", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : LDA #0 : STA (PTR),Y"
DATA "0!0!0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY : INY : STA (PTR),Y"
DATA "__END__", "__END__"

PatternData:

' 1-30: En uzun kompleks loop idiomları
DATA "[->+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[->+>+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[->>>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : INY : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[>+>+<<-]", "INY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "[-<+>]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY"
DATA "[-<->]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : STA (PTR),Y : INY"
DATA "[<+>+>-]", "DEY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y : DEY"
DATA "[-]>", "LDA #0 : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA "[-]<", "LDA #0 : STA (PTR),Y : DEY : BCS *+4 : DEC PTR+1"
DATA "[+]", "LDA #0 : STA (PTR),Y"
DATA "[-]", "LDA #0 : STA (PTR),Y"

' 31-80: C64 Meta / ROM çağrıları
DATA "0++++++++@", "JSR $FFD5 ; KERNAL LOAD"
DATA "0+++++++@", "JSR $FFD8 ; KERNAL SAVE"
DATA "0++++++@", "JSR $E544 : JSR $E518"
DATA "0+++++@", "JSR $E094 : AND #$0F : STA (PTR),Y"
DATA "0++++@", "JSR $E094"
DATA "0+++@", "LDA #3 : JSR $E544"
DATA "0++@", "JSR $E518"
DATA "0+@", "JSR $E544"
DATA "@@", "JSR $E544 : JSR $E518"
DATA "0.@", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $E544"
DATA "@>", "LDA (PTR),Y : JSR $E094 : INY : STA (PTR),Y"
DATA "@.", "LDA (PTR),Y : JSR $FFD2"
DATA "0@", "LDA #0 : JSR $E544"
DATA "+++@", "LDA #3 : JSR $E544"
DATA "0+@>", "JSR $E544 : INY"

' 81-150: Pointer & Value folding (2’den 10’a)
DATA ">>>>>>>>", "TYA : CLC : ADC #8 : TAY : BCC *+4 : INC PTR+1"
DATA ">>>>>>>>>", "TYA : CLC : ADC #9 : TAY : BCC *+4 : INC PTR+1"
DATA ">>>>>>>>>>", "TYA : CLC : ADC #10 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<<", "TYA : SEC : SBC #8 : TAY : BCS *+4 : DEC PTR+1"
DATA "++++++++", "LDA (PTR),Y : CLC : ADC #8 : STA (PTR),Y"
DATA "+++++++++", "LDA (PTR),Y : CLC : ADC #9 : STA (PTR),Y"
DATA "++++++++++", "LDA (PTR),Y : CLC : ADC #10 : STA (PTR),Y"
DATA "--------", "LDA (PTR),Y : SEC : SBC #8 : STA (PTR),Y"
DATA "---------", "LDA (PTR),Y : SEC : SBC #9 : STA (PTR),Y"
DATA "----------", "LDA (PTR),Y : SEC : SBC #10 : STA (PTR),Y"
DATA ">>", "TYA : CLC : ADC #2 : TAY : BCC *+4 : INC PTR+1"
DATA "<<", "TYA : SEC : SBC #2 : TAY : BCS *+4 : DEC PTR+1"
DATA "++", "LDA (PTR),Y : CLC : ADC #2 : STA (PTR),Y"
DATA "--", "LDA (PTR),Y : SEC : SBC #2 : STA (PTR),Y"

' 151-220: Bellek blok işlemleri
DATA "0>0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "!!!!!", "LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY : DEY"
DATA "!!!", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : DEY : DEY"
DATA "!!", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "00", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY"
DATA "!>", "LDA (PTR),Y : INY : STA (PTR),Y"
DATA "?<", "LDA (PTR),Y : DEY : STA (PTR),Y"

' 221-280: Stack & Register
DATA "$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : DEY : STA (PTR),Y"
DATA "$<$%", "LDA (PTR),Y : PHA : DEY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : INY : STA (PTR),Y"
DATA "$0%", "LDA (PTR),Y : PHA : LDA #0 : STA (PTR),Y : PLA : STA (PTR),Y"
DATA "$>", "LDA (PTR),Y : PHA : INY : BNE *+4 : INC PTR+1"
DATA "<%", "TYA : BNE *+4 : DEC PTR+1 : DEY : PLA : STA (PTR),Y"
DATA "0$", "LDA #0 : STA (PTR),Y : PHA"
DATA "+$", "LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : PHA"
DATA "-$", "LDA (PTR),Y : SEC : SBC #1 : STA (PTR),Y : PHA"

' 281-340: Bitwise & Aritmetik
DATA "&&", "LDA (PTR),Y : ASL A : STA (PTR),Y"
DATA "&&&", "LDA (PTR),Y : ASL A : ASL A : STA (PTR),Y"
DATA "||", "LDA (PTR),Y : LSR A : STA (PTR),Y"
DATA "0&", "LDA #0 : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y : DEY"
DATA "0|", "LDA #0 : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "+&+", "LDA (PTR),Y : CLC : ADC #1 : STA $02 : INY : LDA (PTR),Y : ADC $02 : STA (PTR),Y : DEY"
DATA "++&", "LDA (PTR),Y : CLC : ADC #2 : STA $02 : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"

' 341-400: I/O kombinasyonları
DATA ".>", "LDA (PTR),Y : JSR $FFD2 : INY : BNE *+4 : INC PTR+1"
DATA ",>", "JSR $FFCF : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA ".<", "LDA (PTR),Y : JSR $FFD2 : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA ",<", "JSR $FFCF : STA (PTR),Y : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA "..", "LDA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA ",.", "JSR $FFCF : JSR $FFD2 : STA (PTR),Y"
DATA ".0", "LDA (PTR),Y : JSR $FFD2 : LDA #0 : STA (PTR),Y"
DATA "++.", "LDA (PTR),Y : CLC : ADC #2 : JSR $FFD2 : STA (PTR),Y"

' 401-460: Sabit değer atamaları & temizlik
DATA "0++++", "LDA #4 : STA (PTR),Y"
DATA "0+++", "LDA #3 : STA (PTR),Y"
DATA "0++", "LDA #2 : STA (PTR),Y"
DATA "0+", "LDA #1 : STA (PTR),Y"
DATA "0-", "LDA #255 : STA (PTR),Y"
DATA "0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0<0", "LDA #0 : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "^0", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1 : LDA #0 : STA (PTR),Y"
DATA "0^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"

' 461-512: Ekstra optimizasyonlar
DATA "++++++", "LDA (PTR),Y : CLC : ADC #6 : STA (PTR),Y"
DATA "------", "LDA (PTR),Y : SEC : SBC #6 : STA (PTR),Y"
DATA ">>>>>>", "TYA : CLC : ADC #6 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<", "TYA : SEC : SBC #6 : TAY : BCS *+4 : DEC PTR+1"
DATA ">><<", "NOP"
DATA "+-+-", "NOP"
DATA "@@@", "JSR $E544 : JSR $E518 : JSR $E544"
DATA "0..", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA "!!!0", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : LDA #0 : STA (PTR),Y"
DATA "0!0!0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY : INY : STA (PTR),Y"
DATA "__END__", "__END__"