' =============================================================
' UX-MINIMA 6502 UNIQUE PATTERN BANK - REVIEW VERSION
' Generated from uploaded 6502 uxminima/patternbank files.
' Purpose: deduplicate; one PatternData label; one __END__; longest/specific-first order.
' Unique balanced patterns: 207
' Excluded unbalanced patterns: 4
' Conflicted patterns resolved by source priority: 35
' Source priority: patterbankasi1 > uxminima_v2 > patternbank2 > patternbank4 > uxminima/v1.
' NOTE: This is a deduplicated REVIEW bank, not a fully semantic-proofed safe bank.
' =============================================================
PatternData:

DATA ">>>>>>><<<<<<<", "NOP"
DATA "[->+>+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[->+>+<+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "0++++++++++", "LDA #10 : STA (PTR),Y"
DATA "[-]>+>[-]<", "LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "0++++++++@", "JSR $FFD5 ; KERNAL LOAD (full)"
DATA "0+++++++++", "LDA #9 : STA (PTR),Y"
DATA "+++++-----", "NOP ; net zero"
DATA ">>>>>>>>>>", "TYA : CLC : ADC #10 : TAY : BCC *+4 : INC PTR+1"
DATA "++++++++++", "LDA (PTR),Y : CLC : ADC #10 : STA (PTR),Y"
DATA "----------", "LDA (PTR),Y : SEC : SBC #10 : STA (PTR),Y"
DATA "[->>>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : INY : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : DEY"
DATA "[->+>+<<]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY"
DATA "[>+>+<<-]", "INY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : DEY : DEY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y"
DATA "0+++++++@", "JSR $FFD8 ; KERNAL SAVE"
DATA "0>0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0++++++++", "LDA #8 : STA (PTR),Y"
DATA ">>>>>>>>>", "TYA : CLC : ADC #9 : TAY : BCC *+4 : INC PTR+1"
DATA "+++++++++", "LDA (PTR),Y : CLC : ADC #9 : STA (PTR),Y"
DATA "---------", "LDA (PTR),Y : SEC : SBC #9 : STA (PTR),Y"
DATA "[+>[-]<]", "LDA (PTR),Y : BEQ *+8 : INY : LDA #0 : STA (PTR),Y : DEY"
DATA "[<+>+>-]", "DEY : LDA (PTR),Y : TAX : INY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY : LDA (PTR),Y : SEC : SBC (PTR),Y : STA (PTR),Y : DEY"
DATA "0++++++@", "JSR $E544 : JSR $E518 : LDA #$00 : STA $D020 : STA $D021 ; Full CLS + border bg"
DATA ">>>><<<<", "NOP ; pointer cancel"
DATA "0+++++++", "LDA #7 : STA (PTR),Y"
DATA "++++----", "NOP ; value cancel"
DATA "++++++--", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "------++", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"
DATA ">>>>>>>>", "TYA : CLC : ADC #8 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<<", "TYA : SEC : SBC #8 : TAY : BCS *+4 : DEC PTR+1"
DATA "++++++++", "LDA (PTR),Y : CLC : ADC #8 : STA (PTR),Y"
DATA "--------", "LDA (PTR),Y : SEC : SBC #8 : STA (PTR),Y"
DATA "0+++++@", "JSR $E094 : AND #$0F : STA (PTR),Y ; Random 4-bit sensor"
DATA "0>0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0++++++", "LDA #6 : STA (PTR),Y"
DATA ">>>>>>>", "TYA : CLC : ADC #7 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<<", "TYA : SEC : SBC #7 : TAY : BCS *+4 : DEC PTR+1"
DATA "[-][+]", "LDA #0 : STA (PTR),Y"
DATA "[->+<]", "LDA (PTR),Y : CLC : INY : ADC (PTR),Y : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[>+<-]", "INY : LDA (PTR),Y : CLC : DEY : ADC (PTR),Y : INY : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[<+>-]", "DEY : LDA (PTR),Y : CLC : INY : ADC (PTR),Y : DEY : STA (PTR),Y : INY : LDA #0 : STA (PTR),Y"
DATA "[-]<+>", "LDA #0 : STA (PTR),Y : DEY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : INY"
DATA "[-<+>]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : CLC : ADC (PTR),Y : STA (PTR),Y : INY"
DATA "$>$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : DEY : PLA : STA (PTR),Y : DEY : TXA : STA (PTR),Y"
DATA "[->-<]", "LDA (PTR),Y : STA $02 : INY : LDA (PTR),Y : SEC : SBC $02 : STA (PTR),Y : DEY : LDA #0 : STA (PTR),Y"
DATA "[-<->]", "LDA (PTR),Y : TAX : LDA #0 : STA (PTR),Y : DEY : TXA : STA (PTR),Y : INY"
DATA "0++++@", "JSR $E094 ; RND to cell"
DATA ">>>>>>", "TYA : CLC : ADC #6 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<<", "TYA : SEC : SBC #6 : TAY : BCS *+4 : DEC PTR+1"
DATA "++++++", "LDA (PTR),Y : CLC : ADC #6 : STA (PTR),Y"
DATA "------", "LDA (PTR),Y : SEC : SBC #6 : STA (PTR),Y"
DATA "[<->]", "DEY : LDA (PTR),Y : TAX : INY : LDA (PTR),Y : STA (PTR),Y : DEY : TXA : STA (PTR),Y"
DATA "[-]>+", "LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : DEY"
DATA "[-]<+", "LDA #0 : STA (PTR),Y : DEY : LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : INY"
DATA "!!!!!", "LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY : DEY"
DATA "0!0!0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY : INY : STA (PTR),Y"
DATA "0+++@", "LDA #3 : JSR $E544 ; Color change"
DATA "0>!>0", "LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "+++@>", "LDA #3 : JSR $E544 : INY"
DATA "+&+&+", "LDA (PTR),Y : CLC : ADC #1 : STA $02 : INY : LDA (PTR),Y : ADC $02 : STA (PTR),Y : DEY"
DATA "0>0<0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "0>0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0<0<0", "LDA #0 : STA (PTR),Y : DEY : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "++&++", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "--|--", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"
DATA "0++++", "LDA #4 : STA (PTR),Y"
DATA ">>>>>", "TYA : CLC : ADC #5 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<<", "TYA : SEC : SBC #5 : TAY : BCS *+4 : DEC PTR+1"
DATA "+++++", "LDA (PTR),Y : CLC : ADC #5 : STA (PTR),Y"
DATA "-----", "LDA (PTR),Y : SEC : SBC #5 : STA (PTR),Y"
DATA "0[0]", "LDA #0 : STA (PTR),Y : BEQ *+3"
DATA "[-]0", "LDA #0 : STA (PTR),Y"
DATA "$$%%", "LDA (PTR),Y : PHA : PHA : PLA : PLA"
DATA "[<]>", "LDY #0 ; Search back to start of page/boundary"
DATA "[>]<", "LDY #$FF ; Search forward to end of page"
DATA "[-]>", "LDA #0 : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA "[-]<", "LDA #0 : STA (PTR),Y : DEY : BCS *+4 : DEC PTR+1"
DATA "$0$%", "LDA #0 : STA (PTR),Y : PHA : PLA : STA (PTR),Y"
DATA "$>$%", "LDA (PTR),Y : PHA : INY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : DEY : STA (PTR),Y"
DATA "$<$%", "LDA (PTR),Y : PHA : DEY : LDA (PTR),Y : TAX : PLA : STA (PTR),Y : TXA : INY : STA (PTR),Y"
DATA "$+$%", "LDA (PTR),Y : PHA : CLC : ADC #1 : TAX : PLA : STA (PTR),Y"
DATA "!!??", "LDA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : STA (PTR),Y : INY"
DATA "??!!", "LDA (PTR),Y : DEY : STA (PTR),Y : INY : INY : STA (PTR),Y : DEY"
DATA "0$0%", "LDA #0 : PHA : LDA #0 : STA (PTR),Y : PLA : STA (PTR),Y"
DATA "!!!0", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : LDA #0 : STA (PTR),Y"
DATA "!!!>", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : INY : STX (PTR),Y"
DATA "???>", "LDA (PTR),Y : TAX : DEY : STX (PTR),Y : DEY : STX (PTR),Y : DEY : STX (PTR),Y"
DATA "$+$-", "LDA (PTR),Y : PHA : CLC : ADC #1 : STA (PTR),Y : SEC : SBC #2 : STA (PTR),Y : PLA"
DATA "!!!!", "LDA (PTR),Y : STA $02 : INY : STA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY : DEY"
DATA "%<%<", "PLA : STA (PTR),Y : DEY : PLA : STA (PTR),Y : DEY"
DATA "0+@>", "JSR $E544 : INY"
DATA "0++@", "JSR $E518 ; HOME cursor"
DATA "&&&&", "LDA (PTR),Y : ASL A : ASL A : ASL A : STA (PTR),Y ; *8"
DATA "||||", "LDA (PTR),Y : LSR A : LSR A : LSR A : STA (PTR),Y ; /8"
DATA ".0.0", "LDA (PTR),Y : JSR $FFD2 : LDA #0 : STA (PTR),Y : INY : LDA (PTR),Y : JSR $FFD2 : LDA #0 : STA (PTR),Y : DEY"
DATA "+++@", "LDA #3 : JSR $E544"
DATA ">>>0", "TYA : CLC : ADC #3 : TAY : BCC *+4 : INC PTR+1 : LDA #0 : STA (PTR),Y"
DATA "0<<<", "LDA #0 : STA (PTR),Y : TYA : SEC : SBC #3 : TAY : BCS *+4 : DEC PTR+1"
DATA "0+++", "LDA #3 : STA (PTR),Y"
DATA ">><<", "NOP ; > < cancel"
DATA "<><>", "NOP"
DATA "><><", "NOP"
DATA "+-+-", "NOP ; +1-1 cancel"
DATA "++--", "NOP ; ++-- cancel"
DATA "--++", "NOP"
DATA ">>>>", "TYA : CLC : ADC #4 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<<", "TYA : SEC : SBC #4 : TAY : BCS *+4 : DEC PTR+1"
DATA "++++", "LDA (PTR),Y : CLC : ADC #4 : STA (PTR),Y"
DATA "----", "LDA (PTR),Y : SEC : SBC #4 : STA (PTR),Y"
DATA "[@]", "LDA (PTR),Y : BEQ *+5 : JSR $FFD2"
DATA "[0]", "LDA (PTR),Y : BEQ *+3"
DATA "[>]", "INY : LDA (PTR),Y : BEQ *+3"
DATA "[<]", "DEY : LDA (PTR),Y : BEQ *+3"
DATA "[-]", "LDA #0 : STA (PTR),Y"
DATA "[+]", "LDA #0 : STA (PTR),Y"
DATA "@@.", "JSR $E544 : JSR $E518 : LDA (PTR),Y : JSR $FFD2"
DATA "@@0", "JSR $E544 : JSR $E518 : LDA #0 : STA (PTR),Y"
DATA "0@@", "LDA #0 : STA (PTR),Y : JSR $E544 : JSR $E518"
DATA "@@@", "JSR $E544 : JSR $E518 : JSR $E544"
DATA "0!@", "LDA #0 : JSR $E544 : INY"
DATA "@$>", "LDA (PTR),Y : PHA : JSR $E094 : PLA : STA (PTR),Y"
DATA "$0%", "LDA (PTR),Y : PHA : LDA #0 : STA (PTR),Y : PLA : STA (PTR),Y"
DATA "0.@", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $E544"
DATA "0+@", "JSR $E544 ; CLS"
DATA "!!>", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y"
DATA "??<", "LDA (PTR),Y : DEY : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "0^^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "!!!", "LDA (PTR),Y : TAX : INY : STX (PTR),Y : INY : STX (PTR),Y : DEY : DEY"
DATA "???", "LDA (PTR),Y : TAX : DEY : STX (PTR),Y : DEY : STX (PTR),Y : INY : INY"
DATA "0..", "LDA #0 : STA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA "0&0", "LDA #0 : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y : DEY"
DATA "0|0", "LDA #0 : SEC : SBC (PTR),Y : INY : STA (PTR),Y : DEY"
DATA "&&&", "LDA (PTR),Y : ASL A : ASL A : STA (PTR),Y ; *4"
DATA "|||", "LDA (PTR),Y : LSR A : LSR A : STA (PTR),Y ; /4"
DATA ">>!", "INY : INY : LDA (PTR),Y : DEY : DEY : STA (PTR),Y"
DATA "+&+", "LDA (PTR),Y : CLC : ADC #1 : STA $02 : INY : LDA (PTR),Y : ADC $02 : STA (PTR),Y : DEY"
DATA "++&", "LDA (PTR),Y : CLC : ADC #2 : STA $02 : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"
DATA "0>0", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y"
DATA "0<0", "LDA #0 : STA (PTR),Y : DEY : STA (PTR),Y"
DATA "...", "LDA (PTR),Y : JSR $FFD2 : JSR $FFD2 : JSR $FFD2"
DATA ",,,", "JSR $FFCF : STA (PTR),Y : INY : JSR $FFCF : STA (PTR),Y : INY : JSR $FFCF : STA (PTR),Y : DEY : DEY"
DATA "0+0", "LDA #1 : STA (PTR),Y : INY : LDA #0 : STA (PTR),Y : DEY"
DATA "0-0", "LDA #255 : STA (PTR),Y : INY : LDA #0 : STA (PTR),Y : DEY"
DATA "++.", "LDA (PTR),Y : CLC : ADC #2 : JSR $FFD2 : STA (PTR),Y"
DATA "--.", "LDA (PTR),Y : SEC : SBC #2 : JSR $FFD2 : STA (PTR),Y"
DATA "0++", "LDA #2 : STA (PTR),Y"
DATA "++-", "LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y"
DATA "--+", "LDA (PTR),Y : SEC : SBC #1 : STA (PTR),Y"
DATA ">>>", "TYA : CLC : ADC #3 : TAY : BCC *+4 : INC PTR+1"
DATA "<<<", "TYA : SEC : SBC #3 : TAY : BCS *+4 : DEC PTR+1"
DATA "+++", "LDA (PTR),Y : CLC : ADC #3 : STA (PTR),Y"
DATA "---", "LDA (PTR),Y : SEC : SBC #3 : STA (PTR),Y"
DATA "%$", "LDA (PTR),Y : PHA : PLA : STA (PTR),Y"
DATA "$%", "NOP ; redundant"
DATA "@.", "LDA (PTR),Y : JSR $FFD2"
DATA "@@", "JSR $E544 : JSR $E518 ; CLS + HOME"
DATA "0@", "LDA #0 : JSR $E544"
DATA "@0", "JSR $E544 : LDA #0 : STA (PTR),Y"
DATA "!?", "NOP ; Copy right then copy left (no change)"
DATA "@>", "LDA (PTR),Y : JSR $E094 : INY : STA (PTR),Y"
DATA "0$", "LDA #0 : STA (PTR),Y : PHA"
DATA "0%", "PLA : LDA #0"
DATA "$>", "LDA (PTR),Y : PHA : INY : BNE *+4 : INC PTR+1"
DATA "<%", "TYA : BNE *+4 : DEC PTR+1 : DEY : PLA : STA (PTR),Y"
DATA ",.", "JSR $FFCF : JSR $FFD2 : STA (PTR),Y"
DATA "0!", "LDA #0 : INY : STA (PTR),Y : DEY"
DATA "0?", "LDA #0 : DEY : STA (PTR),Y : INY"
DATA ".,", "LDA (PTR),Y : JSR $FFD2 : JSR $FFCF : STA (PTR),Y"
DATA "+$", "LDA (PTR),Y : CLC : ADC #1 : STA (PTR),Y : PHA"
DATA "-$", "LDA (PTR),Y : SEC : SBC #1 : STA (PTR),Y : PHA"
DATA "+%", "LDA (PTR),Y : CLC : ADC #1 : PHA : PLA : STA (PTR),Y"
DATA "-%", "LDA (PTR),Y : SEC : SBC #1 : PHA : PLA : STA (PTR),Y"
DATA "$+", "LDA (PTR),Y : PHA : CLC : ADC #1 : STA (PTR),Y"
DATA "$-", "LDA (PTR),Y : PHA : SEC : SBC #1 : STA (PTR),Y"
DATA "0|", "LDA #0 : SEC : SBC (PTR),Y : STA (PTR),Y ; negate"
DATA "0&", "LDA #0 : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y : DEY"
DATA "^0", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1 : LDA #0 : STA (PTR),Y"
DATA "0^", "LDA #0 : STA (PTR),Y : LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "!>", "LDA (PTR),Y : INY : STA (PTR),Y"
DATA "?<", "LDA (PTR),Y : DEY : STA (PTR),Y"
DATA ".0", "LDA (PTR),Y : JSR $FFD2 : LDA #0 : STA (PTR),Y"
DATA ",0", "JSR $FFCF : LDA #0 : STA (PTR),Y"
DATA "&>", "LDA (PTR),Y : STA $02 : INY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"
DATA "|>", "LDA (PTR),Y : STA $02 : INY : LDA (PTR),Y : SEC : SBC $02 : STA (PTR),Y"
DATA "&<", "LDA (PTR),Y : STA $02 : DEY : LDA (PTR),Y : CLC : ADC $02 : STA (PTR),Y"
DATA "|<", "LDA (PTR),Y : STA $02 : DEY : LDA (PTR),Y : SEC : SBC $02 : STA (PTR),Y"
DATA "!!", "LDA (PTR),Y : INY : STA (PTR),Y : INY : STA (PTR),Y : DEY : DEY"
DATA "??", "LDA (PTR),Y : DEY : STA (PTR),Y : DEY : STA (PTR),Y : INY : INY"
DATA ".>", "LDA (PTR),Y : JSR $FFD2 : INY : BNE *+4 : INC PTR+1"
DATA ",>", "JSR $FFCF : STA (PTR),Y : INY : BNE *+4 : INC PTR+1"
DATA ".<", "LDA (PTR),Y : JSR $FFD2 : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA ",<", "JSR $FFCF : STA (PTR),Y : TYA : BNE *+4 : DEC PTR+1 : DEY"
DATA "&&", "LDA (PTR),Y : ASL A : STA (PTR),Y"
DATA "||", "LDA (PTR),Y : LSR A : STA (PTR),Y"
DATA "^^", "LDA #<MEM : STA PTR : LDA #>MEM : STA PTR+1"
DATA "0+", "LDA #1 : STA (PTR),Y"
DATA "0-", "LDA #255 : STA (PTR),Y"
DATA "..", "LDA (PTR),Y : JSR $FFD2 : JSR $FFD2"
DATA "<>", "NOP ; left then right"
DATA "><", "NOP ; right then left"
DATA "+-", "NOP ; +1 then -1"
DATA "-+", "NOP ; -1 then +1"
DATA "00", "LDA #0 : STA (PTR),Y : INY : STA (PTR),Y : DEY"
DATA ">>", "TYA : CLC : ADC #2 : TAY : BCC *+4 : INC PTR+1"
DATA "<<", "TYA : SEC : SBC #2 : TAY : BCS *+4 : DEC PTR+1"
DATA "++", "LDA (PTR),Y : CLC : ADC #2 : STA (PTR),Y"
DATA "--", "LDA (PTR),Y : SEC : SBC #2 : STA (PTR),Y"
DATA "__END__", "__END__"
